// @ts-check
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";

/**
 * Rules that catch bugs. Not style — prettier already owns that, and a linter
 * arguing about quotes teaches everyone to run it with --fix and stop reading.
 *
 * Type-aware linting is the point of this config. Without project services,
 * no-floating-promises cannot work, and that rule is the reason this exists:
 * a fire-and-forget `void checkAndAwardTitle(...)` shipped in this codebase and
 * swallowed its own failures, which nothing else here would have found.
 */
export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      // Generated by orval from the OpenAPI spec. Lint findings here are
      // instructions to the generator, not to a person, and cannot be fixed in
      // place — the next codegen overwrites them.
      "**/src/generated/**",
      "**/.generated/**",
      "artifacts/cyberplace/src/components/ui/**",
    ],
  },
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // The rule this config is for. An un-awaited promise in a route handler
      // means the response is sent before the work finishes, and a rejection
      // becomes an unhandled one that no error handler sees.
      "@typescript-eslint/no-floating-promises": "error",
      // Passing an async function where a void callback is expected — the
      // caller cannot await it, so the same silence, one level up.
      "@typescript-eslint/no-misused-promises": "error",
      // await on a non-promise usually means a missing await further in.
      "@typescript-eslint/await-thenable": "error",

      // Downgraded, not off. These fire in quantity on existing code and are
      // about tidiness rather than correctness; leaving them as errors would
      // mean the command that reports real bugs exits non-zero either way.
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // Test helpers and config files are not part of the shipped server.
    files: ["**/*.config.{js,ts}", "scripts/**"],
    rules: { "@typescript-eslint/no-floating-promises": "off" },
  },
  {
    files: ["artifacts/cyberplace/src/**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      // The source already carries eslint-disable comments for this rule, which
      // are themselves errors while the plugin is absent. It is also the rule
      // worth having in a React app.
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",

      // JSX handlers are the exception the rule's own docs name. React ignores
      // a handler's return value by design, and `onSubmit={form.handleSubmit(fn)}`
      // — the react-hook-form pattern this app uses everywhere — is a
      // promise-returning function in a void slot on purpose. Left on, this
      // fired 17 times on correct code, which is how a linter gets ignored.
      // Only `attributes` is relaxed: a promise passed anywhere else still errors.
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } },
      ],
    },
  },
);
